# Generated by Django 3.2.16 on 2023-01-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='desc',
            field=models.TextField(default='dddfffds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default='1235'),
            preserve_default=False,
        ),
    ]
